name: Development

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  test:
    uses: khulnasoft-opensource/khulnasoft-opensource/.github/workflows/development.yml@main
